### PR TITLE
Faithful 32x texture pack

### PR DESCRIPTION
**Pull request by STPv22**
this isn't a PvP texture, and I added some details, hope it won't be a problem.

### CODE REVIEW

**Comment by rimmvb** [comment]
This breaks the packs page, I'm not going to merge this until that's fixed

**Comment by STPv22** [comment]
alr

**Comment by STPv22** [comment]
that should fix it

**Comment by STPv22** [comment]
Ive fixed it.

**Comment by rimmvb** [comment]
Remove the description too since other packs dont have any

**Comment by STPv22** [comment]
done

**Pull request merged**
